[database]
filename = 'images.sqlite'

[messages]
start = '''Вітаю!
Гэты бот прызначаны для адпраўкі рандомных мемаў.
Увядзіце /help для атрымання дапамогі.
Папярэджанне! Аўтар ўсё яшчэ не ведае беларускай мовы (не гледзячы на намаганні некаторых людзей). Калі вы знойдзеце памылкі, калі ласка, звяжыцеся з аўтарам:
@istimaldar istimaldar@gmail.com'''
help = '''Бот для адпраўкі рандомных мемаў.
/start - Cкідае стан бота і выводзіць прывітальнае паведамленне.
/help - Выводзіць гэта паведамленне.
/privacy - Паказвае палітыку прыватнасці.
/add_meme - Дазваляе дадаць новы мем.
/memes - Паказвае спіс мемаў. Дазваляе выдаліць мем. Для выбару мему увядзіце нумар ці назву.'''
privacy = '''Бот не выкарыстоўвае і не захоўвае ніякіх дадзеных юзэра.'''
add_meme = '''Для дадання мему адпраўце боту малюнак з подпісам. Подпіс будзе з'яўляцца назвай мему.
Подпіс павінен складацца толькі з лацінскіх і кірылічных літар (уключаючы "ў", "і", выключаючы апостраф), кропак, злучкоў і ніжніх падкрэсьліваньній (прабел нельга).
Таксама подпіс павінна быць унікальным. Спіс існуючых подпісаў можна паглядзець пры дапамозе каманды /memes.'''

[messages.upload]
no_caption = '''Подпіс адсутнічае! Дадайце подпіс да малюнка.'''
no_image = '''Малюнак адсутнічае! Дадайце малюнак.'''
invalid_caption = '''Няверны подпіс! Подпіс павінен складацца толькі з лацінскіх і кирилических літар (уключаючы "ў", "і", выключаючы апостраф), кропак, злучкоў і ніжніх падкрэсьліваньнем (прабел нельга).'''
duplicated_caption = '''Такі подпіс ўжо існуе.'''
success = '''Мем дададзены.'''

[messages.list]
image_select = '''Існуючыя мемы. Для выбару увядзіце нумар ці назву:'''

[messages.select]
invalid_format = '''Няправільны фармат запыту. Калі ласка, увядзіце нумар ці назву мему.'''
not_found = '''Мем не знойдзены.'''
canceled = '''Окей.'''
deleted = '''Выдалена.'''

[messages.buttons]
caption = '''Выберыце дзеянне:'''
delete = '''Выдаліць'''
cancel = '''Назад'''
